[project]
name = "function-calling-vs-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "flask>=3.1.0",
    "mcp>=1.8.0",
    "requests>=2.31.0",
]
